# Generated by Django 2.2 on 2021-09-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='event_comment',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='poster',
            new_name='user',
        ),
    ]
